from KVStore.tests.kvstore.kvstore_simple import SimpleKVStoreTests
from KVStore.tests.kvstore.kvstore_parallel import SimpleKVStoreParallelTests
from KVStore.tests.kvstore.kvstore_race import SimpleKVStoreRaceTests
