# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from KVStore.protos import kv_store_pb2 as KVStore_dot_protos_dot_kv__store__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class KVStoreStub(object):
    """RPCs for key-value server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/KVStore/Get',
                request_serializer=KVStore_dot_protos_dot_kv__store__pb2.GetRequest.SerializeToString,
                response_deserializer=KVStore_dot_protos_dot_kv__store__pb2.GetResponse.FromString,
                )
        self.LPop = channel.unary_unary(
                '/KVStore/LPop',
                request_serializer=KVStore_dot_protos_dot_kv__store__pb2.GetRequest.SerializeToString,
                response_deserializer=KVStore_dot_protos_dot_kv__store__pb2.GetResponse.FromString,
                )
        self.RPop = channel.unary_unary(
                '/KVStore/RPop',
                request_serializer=KVStore_dot_protos_dot_kv__store__pb2.GetRequest.SerializeToString,
                response_deserializer=KVStore_dot_protos_dot_kv__store__pb2.GetResponse.FromString,
                )
        self.Put = channel.unary_unary(
                '/KVStore/Put',
                request_serializer=KVStore_dot_protos_dot_kv__store__pb2.PutRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Append = channel.unary_unary(
                '/KVStore/Append',
                request_serializer=KVStore_dot_protos_dot_kv__store__pb2.AppendRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Redistribute = channel.unary_unary(
                '/KVStore/Redistribute',
                request_serializer=KVStore_dot_protos_dot_kv__store__pb2.RedistributeRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Transfer = channel.unary_unary(
                '/KVStore/Transfer',
                request_serializer=KVStore_dot_protos_dot_kv__store__pb2.TransferRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.AddReplica = channel.unary_unary(
                '/KVStore/AddReplica',
                request_serializer=KVStore_dot_protos_dot_kv__store__pb2.ServerRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.RemoveReplica = channel.unary_unary(
                '/KVStore/RemoveReplica',
                request_serializer=KVStore_dot_protos_dot_kv__store__pb2.ServerRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class KVStoreServicer(object):
    """RPCs for key-value server
    """

    def Get(self, request, context):
        """Necessary for the first subtask
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LPop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RPop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Append(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Redistribute(self, request, context):
        """Necessary for the second subtask
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddReplica(self, request, context):
        """Necessary for the third subtask
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveReplica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KVStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=KVStore_dot_protos_dot_kv__store__pb2.GetRequest.FromString,
                    response_serializer=KVStore_dot_protos_dot_kv__store__pb2.GetResponse.SerializeToString,
            ),
            'LPop': grpc.unary_unary_rpc_method_handler(
                    servicer.LPop,
                    request_deserializer=KVStore_dot_protos_dot_kv__store__pb2.GetRequest.FromString,
                    response_serializer=KVStore_dot_protos_dot_kv__store__pb2.GetResponse.SerializeToString,
            ),
            'RPop': grpc.unary_unary_rpc_method_handler(
                    servicer.RPop,
                    request_deserializer=KVStore_dot_protos_dot_kv__store__pb2.GetRequest.FromString,
                    response_serializer=KVStore_dot_protos_dot_kv__store__pb2.GetResponse.SerializeToString,
            ),
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=KVStore_dot_protos_dot_kv__store__pb2.PutRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Append': grpc.unary_unary_rpc_method_handler(
                    servicer.Append,
                    request_deserializer=KVStore_dot_protos_dot_kv__store__pb2.AppendRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Redistribute': grpc.unary_unary_rpc_method_handler(
                    servicer.Redistribute,
                    request_deserializer=KVStore_dot_protos_dot_kv__store__pb2.RedistributeRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Transfer': grpc.unary_unary_rpc_method_handler(
                    servicer.Transfer,
                    request_deserializer=KVStore_dot_protos_dot_kv__store__pb2.TransferRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AddReplica': grpc.unary_unary_rpc_method_handler(
                    servicer.AddReplica,
                    request_deserializer=KVStore_dot_protos_dot_kv__store__pb2.ServerRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RemoveReplica': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveReplica,
                    request_deserializer=KVStore_dot_protos_dot_kv__store__pb2.ServerRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'KVStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KVStore(object):
    """RPCs for key-value server
    """

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KVStore/Get',
            KVStore_dot_protos_dot_kv__store__pb2.GetRequest.SerializeToString,
            KVStore_dot_protos_dot_kv__store__pb2.GetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LPop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KVStore/LPop',
            KVStore_dot_protos_dot_kv__store__pb2.GetRequest.SerializeToString,
            KVStore_dot_protos_dot_kv__store__pb2.GetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RPop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KVStore/RPop',
            KVStore_dot_protos_dot_kv__store__pb2.GetRequest.SerializeToString,
            KVStore_dot_protos_dot_kv__store__pb2.GetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KVStore/Put',
            KVStore_dot_protos_dot_kv__store__pb2.PutRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Append(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KVStore/Append',
            KVStore_dot_protos_dot_kv__store__pb2.AppendRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Redistribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KVStore/Redistribute',
            KVStore_dot_protos_dot_kv__store__pb2.RedistributeRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Transfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KVStore/Transfer',
            KVStore_dot_protos_dot_kv__store__pb2.TransferRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddReplica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KVStore/AddReplica',
            KVStore_dot_protos_dot_kv__store__pb2.ServerRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveReplica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KVStore/RemoveReplica',
            KVStore_dot_protos_dot_kv__store__pb2.ServerRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
