# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KVStore/protos/kv-store-shardmaster.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)KVStore/protos/kv-store-shardmaster.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1d\n\x0bJoinRequest\x12\x0e\n\x06server\x18\x01 \x01(\t\"\x1e\n\x0cLeaveRequest\x12\x0e\n\x06server\x18\x01 \x01(\t\"\x1b\n\x0cQueryRequest\x12\x0b\n\x03key\x18\x01 \x01(\r\"\x1f\n\rQueryResponse\x12\x0e\n\x06server\x18\x01 \x01(\t\"*\n\x13JoinReplicaResponse\x12\x13\n\x04role\x18\x01 \x01(\x0e\x32\x05.Role\"A\n\x13QueryReplicaRequest\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x1d\n\toperation\x18\x02 \x01(\x0e\x32\n.Operation*\x1f\n\x04Role\x12\n\n\x06MASTER\x10\x00\x12\x0b\n\x07REPLICA\x10\x01*?\n\tOperation\x12\x07\n\x03GET\x10\x00\x12\x07\n\x03PUT\x10\x01\x12\n\n\x06\x41PPEND\x10\x02\x12\t\n\x05L_POP\x10\x03\x12\t\n\x05R_POP\x10\x04\x32\x86\x02\n\x0bShardMaster\x12.\n\x04Join\x12\x0c.JoinRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x30\n\x05Leave\x12\r.LeaveRequest\x1a\x16.google.protobuf.Empty\"\x00\x12(\n\x05Query\x12\r.QueryRequest\x1a\x0e.QueryResponse\"\x00\x12\x33\n\x0bJoinReplica\x12\x0c.JoinRequest\x1a\x14.JoinReplicaResponse\"\x00\x12\x36\n\x0cQueryReplica\x12\x14.QueryReplicaRequest\x1a\x0e.QueryResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'KVStore.protos.kv_store_shardmaster_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROLE._serialized_start=310
  _ROLE._serialized_end=341
  _OPERATION._serialized_start=343
  _OPERATION._serialized_end=406
  _JOINREQUEST._serialized_start=74
  _JOINREQUEST._serialized_end=103
  _LEAVEREQUEST._serialized_start=105
  _LEAVEREQUEST._serialized_end=135
  _QUERYREQUEST._serialized_start=137
  _QUERYREQUEST._serialized_end=164
  _QUERYRESPONSE._serialized_start=166
  _QUERYRESPONSE._serialized_end=197
  _JOINREPLICARESPONSE._serialized_start=199
  _JOINREPLICARESPONSE._serialized_end=241
  _QUERYREPLICAREQUEST._serialized_start=243
  _QUERYREPLICAREQUEST._serialized_end=308
  _SHARDMASTER._serialized_start=409
  _SHARDMASTER._serialized_end=671
# @@protoc_insertion_point(module_scope)
