# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from KVStore.protos import kv_store_shardmaster_pb2 as KVStore_dot_protos_dot_kv__store__shardmaster__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class ShardMasterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Join = channel.unary_unary(
                '/ShardMaster/Join',
                request_serializer=KVStore_dot_protos_dot_kv__store__shardmaster__pb2.JoinRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Leave = channel.unary_unary(
                '/ShardMaster/Leave',
                request_serializer=KVStore_dot_protos_dot_kv__store__shardmaster__pb2.LeaveRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Query = channel.unary_unary(
                '/ShardMaster/Query',
                request_serializer=KVStore_dot_protos_dot_kv__store__shardmaster__pb2.QueryRequest.SerializeToString,
                response_deserializer=KVStore_dot_protos_dot_kv__store__shardmaster__pb2.QueryResponse.FromString,
                )
        self.JoinReplica = channel.unary_unary(
                '/ShardMaster/JoinReplica',
                request_serializer=KVStore_dot_protos_dot_kv__store__shardmaster__pb2.JoinRequest.SerializeToString,
                response_deserializer=KVStore_dot_protos_dot_kv__store__shardmaster__pb2.JoinReplicaResponse.FromString,
                )
        self.QueryReplica = channel.unary_unary(
                '/ShardMaster/QueryReplica',
                request_serializer=KVStore_dot_protos_dot_kv__store__shardmaster__pb2.QueryReplicaRequest.SerializeToString,
                response_deserializer=KVStore_dot_protos_dot_kv__store__shardmaster__pb2.QueryResponse.FromString,
                )


class ShardMasterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Join(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Leave(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinReplica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryReplica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShardMasterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Join': grpc.unary_unary_rpc_method_handler(
                    servicer.Join,
                    request_deserializer=KVStore_dot_protos_dot_kv__store__shardmaster__pb2.JoinRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Leave': grpc.unary_unary_rpc_method_handler(
                    servicer.Leave,
                    request_deserializer=KVStore_dot_protos_dot_kv__store__shardmaster__pb2.LeaveRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=KVStore_dot_protos_dot_kv__store__shardmaster__pb2.QueryRequest.FromString,
                    response_serializer=KVStore_dot_protos_dot_kv__store__shardmaster__pb2.QueryResponse.SerializeToString,
            ),
            'JoinReplica': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinReplica,
                    request_deserializer=KVStore_dot_protos_dot_kv__store__shardmaster__pb2.JoinRequest.FromString,
                    response_serializer=KVStore_dot_protos_dot_kv__store__shardmaster__pb2.JoinReplicaResponse.SerializeToString,
            ),
            'QueryReplica': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryReplica,
                    request_deserializer=KVStore_dot_protos_dot_kv__store__shardmaster__pb2.QueryReplicaRequest.FromString,
                    response_serializer=KVStore_dot_protos_dot_kv__store__shardmaster__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ShardMaster', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ShardMaster(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Join(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ShardMaster/Join',
            KVStore_dot_protos_dot_kv__store__shardmaster__pb2.JoinRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Leave(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ShardMaster/Leave',
            KVStore_dot_protos_dot_kv__store__shardmaster__pb2.LeaveRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ShardMaster/Query',
            KVStore_dot_protos_dot_kv__store__shardmaster__pb2.QueryRequest.SerializeToString,
            KVStore_dot_protos_dot_kv__store__shardmaster__pb2.QueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def JoinReplica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ShardMaster/JoinReplica',
            KVStore_dot_protos_dot_kv__store__shardmaster__pb2.JoinRequest.SerializeToString,
            KVStore_dot_protos_dot_kv__store__shardmaster__pb2.JoinReplicaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryReplica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ShardMaster/QueryReplica',
            KVStore_dot_protos_dot_kv__store__shardmaster__pb2.QueryReplicaRequest.SerializeToString,
            KVStore_dot_protos_dot_kv__store__shardmaster__pb2.QueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
